/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    products: Product;
  };
  globals: {
    navbar: Navbar;
    footer: Footer;
    login: Login;
    register: Register;
    productPage: ProductPage;
    homepage: Homepage;
  };
}
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  purchases?: string[] | Product[];
  cart: {
    items: {
      product?: string | Product;
      quantity?: number;
      id?: string;
    }[];
  };
  roles: 'admin' | 'user';
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Product {
  id: string;
  name: string;
  createdBy?: string | User;
  stock: number;
  price?: number;
  date: string;
  description: string;
  slider: {
    src?: string;
    alt?: string;
    id?: string;
  }[];
  breadcrumbs: {
    name?: string;
    id?: string;
  }[];
  details: {
    name?: string;
    value?: string;
    id?: string;
    blockName?: string;
    blockType: 'information';
  }[];
  tags: {
    id?: string;
    name?: string;
  }[];
  reviews: {
    review: {
      user?: string | User;
      opinion?: string;
      average?: number;
    };
    id?: string;
  }[];
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface Navbar {
  id: string;
  categories: {
    id?: string;
    name?: string;
    featured: {
      name?: string;
      href?: string;
      src?: string;
      alt?: string;
      id?: string;
    }[];
    sections: {
      id?: string;
      name?: string;
      items: {
        name?: string;
        href?: string;
        id?: string;
      }[];
    }[];
  }[];
  pages: {
    name?: string;
    href?: string;
    id?: string;
  }[];
}
export interface Footer {
  id: string;
  fixedContent: {
    text?: string;
    socialLinks: {
      href?: string;
      id?: string;
    }[];
  };
  Colunms: {
    title?: string;
    content: {
      title?: string;
      href?: string;
      id?: string;
    }[];
    id?: string;
  }[];
}
export interface Login {
  id: string;
  title: string;
  emailInput: {
    label: string;
    placeholder: string;
    error: string;
  };
  passwordInput: {
    label: string;
    placeholder: string;
    error: string;
  };
  titleSubmit: string;
}
export interface Register {
  id: string;
  title: string;
  nameInput: {
    label: string;
    placeholder: string;
    error: string;
  };
  lastnameInput: {
    label: string;
    placeholder: string;
    error: string;
  };
  emailInput: {
    label: string;
    placeholder: string;
    error: string;
  };
  passwordInput: {
    label: string;
    placeholder: string;
    error: string;
  };
  passwordConfirmInput: {
    label: string;
    placeholder: string;
    error: string;
  };
  checkboxes: {
    label?: string;
    id?: string;
  }[];
  titleSubmit: string;
}
export interface ProductPage {
  id: string;
  information?: string;
  date?: string;
  button?: string;
}
export interface Homepage {
  id: string;
  header: {
    title: string;
    title2?: string;
    paragraph?: string;
    anchor1: string;
    anchor2: string;
    image: {
      src?: string;
      alt?: string;
    };
  };
  inlineProducts: {
    title?: string;
    products?: string[] | Product[];
  };
  brands: {
    title: string;
    brands: {
      src?: string;
      alt?: string;
      id?: string;
    }[];
  };
  newArrivals: {
    title?: string;
    products?: string[] | Product[];
  };
  newsLetter: {
    title: string;
    shortTitle: string;
    emailInput: {
      label?: string;
      placeholder?: string;
      inputHelper?: string;
    };
    buttonLabel?: string;
  };
}
